services:
  spring-boot-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - CACHEDB_HOST=cachedb
      - CACHEDB_PORT=6379
      - CACHEDB_PASSWORD=${CACHEDB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
    volumes:
      - .:/app
    depends_on:
      - cachedb 
      - db

  cachedb:
    image: redis:6.2.17-alpine3.21
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${CACHEDB_PASSWORD}
    networks:
      - app-network

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
